id:
program_id:
client_id:
provider_id:
owner_id:
worker_id:
resolver_id:
state:
complainant_name:
complainant_id:
provider_number:
reason_name:
referred_to:
complainant_type_id:
complainant_relationship_id:
reason_id:
description:
created_at:
updated_at:
deleted_at:
created_by:
updated_by:
deleted_by:
resolved_on:
occurred_on:
case_manager_id:
service_ids:
service_delivery_problem_ids:
contract_problem_ids:
billed_on:
documented_on:
due_on:
completed_on:
started_on:
ended_on:
aps_contacted_on:
hospitalizations_within_30_days: